name: CI

on: [push, pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        working-directory: backend/
        run: npm run test